all: main.py
	python3 main.py
clean:
	sudo rm -r ../test/result/blur
	sudo rm -r ../test/result/threshold
	sudo rm -r ../test/result/adathreshold
	sudo rm -r ../test/result/thresoldcontour
	sudo rm -r ../test/result/thresoldContourExternal
	sudo rm -r ../test/result/cannycontour
	sudo rm -r ../test/result/cannyContourExternal
	mkdir ../test/result/blur
	mkdir ../test/result/threshold
	mkdir ../test/result/adathreshold
	mkdir ../test/result/thresoldcontour
	mkdir ../test/result/thresoldContourExternal
	mkdir ../test/result/cannycontour
	mkdir ../test/result/cannyContourExternal
